#!/usr/bin/env bash
#Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo /var/www/html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
