#!/usr/bin/env bash
#Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
