#!/usr/bin/env bash
#Install your load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 2432-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 2432-web-02 54.90.205.145 check\n\tserver 2432-web-01    35.190.174.89 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
