#!/usr/bin/env bash
# #This script is displaying To infinity and beyond indefinitely and capturing SIGTERM
trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
