#!/usr/bin/env bash
# This script displays different strings using if and else conditions
c=1
while [ $c -le 10 ]
do
	if [ $c = 4 ]
	then
		echo "bad luck"
	elif [ $c = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	c=$((c = c + 1))
done