#!/usr/bin/env bash
# This script displays the numbers 1 to 10 and different strings using if and else conditions
c=1
while [ $c -le 20 ]
do
	echo $c
	case $c in

		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	c=$((c = c + 1))
done

